//
// Autogenerated by Laurine - by Jiri Trecak ( http://jiritrecak.com, @jiritrecak )
// Do not change this file manually!
//


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Imports

import Foundation


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Localizations


public struct Localizations {


    public struct Global {

        /// Base translation: Messages
        public static var AppName : String = NSLocalizedString("global.app_name", comment: "")

        /// Base translation: Cancel
        public static var Cancel : String = NSLocalizedString("global.cancel", comment: "")

        /// Base translation: Ok
        public static var Ok : String = NSLocalizedString("global.ok", comment: "")

        /// Base translation: Error
        public static var Error : String = NSLocalizedString("global.error", comment: "")

    }

    public struct MessageList {

        /// Base translation: Delete
        public static var Delete : String = NSLocalizedString("message_list.delete", comment: "")

    }
}